---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: playbook.yml
  hosts: telefonesnet.com.br
  roles_path: roles
  requirements_path: requirements.yml
  additional_copy_path:
    - ./vars

platforms:
  - name: ubuntu/xenial64
    driver_plugin: vagrant
    driver_config:
      box: ubuntu/xenial64 

suites:
  - name: default
